# Use git and branch master to update site
backend:
  name: git-gateway
  branch: master

media_folder: "images/galleries" # Folder for uploading images

collections:
  - label: "Gallery"
    name: "galleries"
    create: true
    folder: "_galleries"
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title",  widget: "string"}
      - label: "Images"
        name: "arts"
        widget: "list"
        fields:
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Order", name: "order", widget: "number"}
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Artist", name: "artist", widget: "string", required: false}
          - {label: "Description", name: "description", widget: "text", required: false}
  - label: "Navigation Elements"
    name: "navigation"
    create: false
    delete: false
    folder: "_data"
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "hidden"}
      - label: "Entries"
        name: "entries"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Link", name: "href", widget: "string"}
